export const navItems = [
  { id: 1, name: 'Dashboard', iconPath: '/icon/home.svg', route: '/dashboard' },
  { id: 2, name: 'Orders', iconPath: '/icon/order.svg', route: '/orders' },
  {
    id: 3,
    name: 'Inventory',
    iconPath: '/icon/inventory.png',
    route: '/inventory',
  },
  {
    id: 5,
    name: 'Report',
    iconPath: '/icon/report.svg',
    route: '/report-analytics',
  },
  {
    id: 6,
    name: 'Settings',
    iconPath: '/icon/settings.svg',
    route: '/settings',
  },
];

export const recentOders = [
  {
    id: 1,
    orderId: 'Order #123',
    customerName: 'Clinton Frank',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
  {
    id: 2,
    orderId: 'Order #124',
    customerName: 'Clinton Frank',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Shipped',
  },
  {
    id: 3,
    orderId: 'Order #125',
    customerName: 'Clinton Frank',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Delivered',
  },
  {
    id: 4,
    orderId: 'Order #126',
    customerName: 'Clinton Frank',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Delivered',
  },
  {
    id: 5,
    orderId: 'Order #127',
    customerName: 'Clinton Frank',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
  {
    id: 6,
    orderId: 'Order #128',
    customerName: 'Clinton Frank',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Delivered',
  },
  {
    id: 7,
    orderId: 'Order #129',
    customerName: 'Clinton Frank',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
];

export const inventoryItems = [
  {
    id: 1,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 2,
    itemsInStock: 'Pots',
    category: 'Kitchen Utensil',
    stockLevel: '8 Units',
    price: '2,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 3,
    itemsInStock: 'Corporate Shoes',
    category: 'Wears',
    stockLevel: '15 Units',
    price: '21,500',
    lastUpdated: 'March 1, 2025',
    actions: 'Restock',
    status: 'In Stock',
  },
  {
    id: 4,
    itemsInStock: 'Balencial Top',
    category: 'Wears',
    stockLevel: '4 Units',
    price: '2,500',
    lastUpdated: 'March 1, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 5,
    itemsInStock: 'Cut & Join Jeans',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '2,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 6,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '2,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 7,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
];

export const orderVolume = [
  {
    id: 1,
    orderPlaced: 45,
    date: 'May 13, 2025',
    orderCompleted: 39,
  },
  {
    id: 2,
    orderPlaced: 29,
    date: 'March 5, 2025',
    orderCompleted: 27,
  },
  {
    id: 3,
    orderPlaced: 32,
    date: 'March 11, 2025',
    orderCompleted: 26,
  },
  {
    id: 4,
    orderPlaced: 18,
    date: 'April 23, 2025',
    orderCompleted: 18,
  },
  {
    id: 5,
    orderPlaced: 30,
    date: 'May 23, 2025',
    orderCompleted: 15,
  },
];

export const stockTurnoer = [
  {
    id: 1,
    products: 'Necklace',
    productRemain: 24,
    productSold: 2,
  },
  {
    id: 1,
    products: 'Nike Sneakers',
    productRemain: 24,
    productSold: 2,
  },
  {
    id: 1,
    products: 'Pots',
    productRemain: 16,
    productSold: 8,
  },
  {
    id: 4,
    products: 'Corporate Shoes',
    productRemain: 24,
    productSold: 30,
  },
  {
    id: 5,
    products: 'Nike Sneakers',
    productRemain: 5,
    productSold: 14,
  },
];

export const reportSummary = [
  {
    id: 1,
    Product: 'Nike Sneakers',
    revenue: 20000,
    stockStatus: 'In Stock',
    productSold: 120,
  },
  {
    id: 2,
    Product: 'Hand Bag',
    revenue: 40000,
    stockStatus: 'Low Stock',
    productSold: 400,
  },
  {
    id: 3,
    Product: 'Balenciaga',
    revenue: 50000,
    stockStatus: 'In Stock',
    productSold: 450,
  },
  {
    id: 4,
    Product: 'Addidas Sneakers',
    revenue: 15000,
    stockStatus: 'In Stock',
    productSold: 100,
  },
];
export const paymentStatus = [
  {
    id: 1,
    amount: '8,000',
    date: 'May 23, 2025',
    status: 'Reconciled',
  },
  {
    id: 2,
    amount: '6,000',
    date: 'May 23, 2025',
    status: 'Unreconcile',
  },
  {
    id: 3,
    amount: '10,000',
    date: 'May 23, 2025',
    status: 'Reconciled',
  },
  {
    id: 4,
    amount: '2,000',
    date: 'May 23, 2025',
    status: 'Unreconcile',
  },
  {
    id: 5,
    amount: '8,000',
    date: 'May 23, 2025',
    status: 'Reconciled',
  },
];

export const tasks = [
  {
    id: 1,
    overview: 'Follow up order #123',
    dueDate: 'May 23, 2025',
    order: 'Orders',
    status: 'To Do',
    priority: 'High',
  },
  {
    id: 2,
    overview: 'Follow up order #123',
    dueDate: 'May 23, 2025',
    order: 'Orders',
    status: 'To Do',
    priority: 'High',
  },
  {
    id: 3,
    overview: 'Follow up order #123',
    dueDate: 'May 23, 2025',
    order: 'Orders',
    status: 'To Do',
    priority: 'High',
  },
  {
    id: 4,
    overview: 'Follow up order #123',
    dueDate: 'May 23, 2025',
    order: 'Orders',
    status: 'To Do',
    priority: 'High',
  },
  {
    id: 5,
    overview: 'Follow up order #123',
    dueDate: 'May 23, 2025',
    order: 'Orders',
    status: 'To Do',
    priority: 'High',
  },
  {
    id: 6,
    overview: 'Follow up order #123',
    dueDate: 'May 23, 2025',
    order: 'Orders',
    status: 'To Do',
    priority: 'High',
  },
  {
    id: 7,
    overview: 'Follow up order #123',
    dueDate: 'May 23, 2025',
    order: 'Orders',
    status: 'To Do',
    priority: 'High',
  },
];

export const user = {
  id: '1',
  name: `Jessie's Tees`,
  email: 'jessie@gmail.com',
  businessPlan: 'Premium Plan',
};
