export const navItems = [
  { id: 1, name: 'Dashboard', iconPath: '/icon/home.svg', route: '/dashboard' },
  { id: 2, name: 'Orders', iconPath: '/icon/order.svg', route: '/orders' },
  {
    id: 3,
    name: 'Inventory',
    iconPath: '/icon/inventory.png',
    route: '/inventory',
  },
  {
    id: 5,
    name: 'Report',
    iconPath: '/icon/report.svg',
    route: '/report-analytics',
  },
  {
    id: 6,
    name: 'Settings',
    iconPath: '/icon/settings.svg',
    route: '/settings',
  },
];

export const inventoryItems = [
  {
    id: 10011,
    name: 'Claud Sneakers',
    category: 'Wears',
    stock: 8,
    price: 21500,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 10001,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 13,
    price: 1500,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 10002,
    name: 'Pots',
    category: 'Kitchen Utensil',
    stock: 9,
    price: 5500,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 20003,
    name: 'Corporate Shoes',
    category: 'Wears',
    stock: 5,
    price: 21500,
    status: 'pending',
    lastUpdated: 'March 1, 2025',
  },
  {
    id: 162777,
    name: 'Vodi Top',
    category: 'Wears',
    stock: 4,
    price: 3500,
    status: 'pending',
    lastUpdated: 'March 1, 2025',
  },
  {
    id: 512111,
    name: 'Cut & Join Jeans',
    category: 'Wears',
    stock: 11,
    price: 4500,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 2213333,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 8,
    price: 2500,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 7,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 8,
    price: 3000,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 44,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 15,
    price: 14000,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 43,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 12,
    price: 13000,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 42,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 22,
    price: 46000,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 41,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 2,
    price: 12000,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 40,
    status: 'pending',
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 8,
    price: 14000,
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 8,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 8,
    price: 19000,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 9,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 3,
    price: 2100,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 10,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 2,
    price: 7000,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 11,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 20,
    price: 5000,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 12,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 8,
    price: 2000,
    status: 'pending',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 13,
    name: 'Nike Sneakers',
    category: 'Wears',
    stock: 1,
    price: 30000,
    status: 'success',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 14,
    name: 'viadas',
    category: 'Wears',
    stock: 4,
    price: 21000,
    status: 'success',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 15,
    name: 'BG Wears',
    category: 'Wears',
    stock: 8,
    price: 50000,
    status: 'success',
    lastUpdated: 'March 23, 2025',
  },
  {
    id: 16,
    name: 'Aba Sneakers',
    category: 'Wears',
    stock: 2,
    price: 23000,
    status: 'success',
    lastUpdated: 'April 23, 2025',
  },
];

export const orderVolume = [
  {
    id: 1,
    orderPlaced: 45,
    date: 'May 13, 2025',
    orderCompleted: 39,
  },
  {
    id: 2,
    orderPlaced: 29,
    date: 'March 5, 2025',
    orderCompleted: 27,
  },
  {
    id: 3,
    orderPlaced: 32,
    date: 'March 11, 2025',
    orderCompleted: 26,
  },
  {
    id: 4,
    orderPlaced: 18,
    date: 'April 23, 2025',
    orderCompleted: 18,
  },
  {
    id: 5,
    orderPlaced: 30,
    date: 'May 23, 2025',
    orderCompleted: 15,
  },
];

export const stockTurnoer = [
  {
    id: 1,
    products: 'Necklace',
    productRemain: 24,
    productSold: 2,
  },
  {
    id: 1,
    products: 'Nike Sneakers',
    productRemain: 24,
    productSold: 2,
  },
  {
    id: 1,
    products: 'Pots',
    productRemain: 16,
    productSold: 8,
  },
  {
    id: 4,
    products: 'Corporate Shoes',
    productRemain: 24,
    productSold: 30,
  },
  {
    id: 5,
    products: 'Nike Sneakers',
    productRemain: 5,
    productSold: 14,
  },
];

export const reportSummary = [
  {
    id: 1,
    Product: 'Nike Sneakers',
    revenue: 20000,
    stockStatus: 'In Stock',
    productSold: 120,
  },
  {
    id: 2,
    Product: 'Hand Bag',
    revenue: 40000,
    stockStatus: 'Low Stock',
    productSold: 400,
  },
  {
    id: 3,
    Product: 'Vodi',
    revenue: 50000,
    stockStatus: 'In Stock',
    productSold: 450,
  },
  {
    id: 4,
    Product: 'Addidas Sneakers',
    revenue: 15000,
    stockStatus: 'In Stock',
    productSold: 100,
  },
];
export const paymentStatus = [
  {
    id: 1,
    amount: '8,000',
    date: 'May 23, 2025',
    status: 'Reconciled',
  },
  {
    id: 2,
    amount: '6,000',
    date: 'May 23, 2025',
    status: 'Unreconcile',
  },
  {
    id: 3,
    amount: '10,000',
    date: 'May 23, 2025',
    status: 'Reconciled',
  },
  {
    id: 4,
    amount: '2,000',
    date: 'May 23, 2025',
    status: 'Unreconcile',
  },
  {
    id: 5,
    amount: '8,000',
    date: 'May 23, 2025',
    status: 'Reconciled',
  },
];

export const user = {
  id: '1',
  name: `Jessie's Tees`,
  email: 'simeonstat@gmail.com',
  businessPlan: 'Premium Plan',
};

export const aboutBiz = {
  title: 'About BizEase',

  subTitle: `Running a business is hard enough — managing your orders and inventory shouldn't be. That's where BizEase comes in.`,

  sub: `We created BizEase with one simple goal: to take the stress out of business management for small and medium-sized enterprises. Whether you're juggling sales, shipping, or stock levels, BizEase gives you the tools to stay in control — all from one intuitive platform.`,

  missionHead: 'Our Mission',
  missionSub: `At BizEase, we believe powerful business tools shouldn't come with a steep learning curve. That is why we built a platform thats easy to use, efficient, and designed to grow with your business.`,

  missionSub2: `Born out of frustration with clunky spreadsheets and over-complicated software, BizEase was created to simplify daily operations — so business owners can focus on what truly matters: growing their business and serving their customers.`,

  amazingHead: 'What Makes BizEase Amazing?',
  amazingSub: `Here is what you can expect when you switch to BizEase:`,

  amazingList: [
    '✅ Smart Order Management Track orders from start to finish, keep your customers in the loop, and never miss a sale.',
    '📦 Real-Time Inventory Tracking - Know exactly what is in stock, what is running low, and when to reorder — all in real time.',
    '🔗 Seamless Integration - Easily connect with your existing tools and platforms — no tech headaches.',
    '📊 Insightful Reports & Dashboards - Get a clear picture of your business with customizable analytics and performance metrics.',
    '⏱️ Time-Saving Automation - Automate repetitive tasks and cut down on manual work, so you can focus on growth.',
    '🔒 Secure and Reliable - Your data is safe with us. BizEase uses top-grade security so you can operate with peace of mind.',
    '📱 Access Anywhere, Anytime - Manage your business from your laptop, tablet, or phone — wherever you are.',
  ],

  builtForH: 'Built for Business Owners Like You',
  builtsub: `Whether you're managing a retail shop, running an online store, or overseeing multiple warehouses, BizEase adapts to your needs — not the other way around. We're here to make your life easier, your operations smoother, and your growth unstoppable.`,

  ready: 'Ready to simplify your business?',
};
