export const navItems = [
  { id: 1, name: 'Dashboard', iconPath: '/icon/home.svg', route: '/dashboard' },
  { id: 2, name: 'Orders', iconPath: '/icon/order.svg', route: '/orders' },
  {
    id: 3,
    name: 'Inventory',
    iconPath: '/icon/inventory.png',
    route: '/inventory',
  },
  {
    id: 5,
    name: 'Report',
    iconPath: '/icon/report.svg',
    route: '/report-analytics',
  },
  {
    id: 6,
    name: 'Settings',
    iconPath: '/icon/settings.svg',
    route: '/settings',
  },
];

export const recentOrders = [
  {
    id: 1,
    orderId: 'Order #123',
    customerName: 'Clinton',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
  {
    id: 2,
    orderId: 'Order #124',
    customerName: ' Frank',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Shipped',
  },
  {
    id: 3,
    orderId: 'Order #125',
    customerName: 'Joe',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Delivered',
  },
  {
    id: 4,
    orderId: 'Order #126',
    customerName: 'Don',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Delivered',
  },
  {
    id: 5,
    orderId: 'Order #127',
    customerName: 'Esther',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
  {
    id: 6,
    orderId: 'Order #128',
    customerName: 'Adeola',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Delivered',
  },
  {
    id: 7,
    orderId: 'Order #129',
    customerName: 'Joel',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'delivered',
  },
  {
    id: 8,
    orderId: 'Order #120',
    customerName: 'Monica',
    total: '5,110',
    date: 'June 23, 2025',
    status: 'delivered',
  },
  {
    id: 9,
    orderId: 'Order #131',
    customerName: 'Ogunlabi',
    total: '510,000',
    date: 'March 1, 2025',
    status: 'Pending',
  },
  {
    id: 10,
    orderId: 'Order #132',
    customerName: 'Uko',
    total: '9,000',
    date: 'Feb 23, 2025',
    status: 'delivered',
  },
  {
    id: 11,
    orderId: 'Order #133',
    customerName: 'Isiaq',
    total: '3,000',
    date: 'April 23, 2025',
    status: 'delivered',
  },
  {
    id: 12,
    orderId: 'Order #134',
    customerName: 'John',
    total: '57,000',
    date: 'March 23, 2025',
    status: 'delivered',
  },
  {
    id: 13,
    orderId: 'Order #134',
    customerName: 'Chuks',
    total: '4,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
  {
    id: 14,
    orderId: 'Order #135',
    customerName: 'Joel',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
  {
    id: 15,
    orderId: 'Order #136',
    customerName: 'Kunle',
    total: '50,000',
    date: 'March 23, 2025',
    status: 'delivered',
  },
  {
    id: 16,
    orderId: 'Order #137',
    customerName: 'Orunminla',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'delivered',
  },
  {
    id: 17,
    orderId: 'Order #138',
    customerName: 'Ugo',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
  {
    id: 18,
    orderId: 'Order #39',
    customerName: 'Mike',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
  {
    id: 19,
    orderId: 'Order #401',
    customerName: 'Zoe',
    total: '5,000',
    date: 'March 01, 2025',
    status: 'delivered',
  },
  {
    id: 20,
    orderId: 'Order #444',
    customerName: 'Zoe',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
  {
    id: 21,
    orderId: 'Order #129',
    customerName: 'Joel',
    total: '5,000',
    date: 'March 23, 2025',
    status: 'Pending',
  },
];

export const inventoryItems = [
  {
    id: 1,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 2,
    itemsInStock: 'Pots',
    category: 'Kitchen Utensil',
    stockLevel: '8 Units',
    price: '2,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 3,
    itemsInStock: 'Corporate Shoes',
    category: 'Wears',
    stockLevel: '15 Units',
    price: '21,500',
    lastUpdated: 'March 1, 2025',
    actions: 'Restock',
    status: 'In Stock',
  },
  {
    id: 4,
    itemsInStock: 'Vodi Top',
    category: 'Wears',
    stockLevel: '4 Units',
    price: '2,500',
    lastUpdated: 'March 1, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 5,
    itemsInStock: 'Cut & Join Jeans',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '2,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 6,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '2,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 7,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 44,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 43,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 42,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 41,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 40,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 8,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 9,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 10,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'In Stock',
  },
  {
    id: 11,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'in Stock',
  },
  {
    id: 12,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 13,
    itemsInStock: 'Nike Sneakers',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 14,
    itemsInStock: 'viadas',
    category: 'Wears',
    stockLevel: '9 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'In Stock',
  },
  {
    id: 15,
    itemsInStock: 'BG Wears',
    category: 'Wears',
    stockLevel: '8 Units',
    price: '21,500',
    lastUpdated: 'March 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
  {
    id: 16,
    itemsInStock: 'Aba Sneakers',
    category: 'Wears',
    stockLevel: '2 Units',
    price: '23,500',
    lastUpdated: 'April 23, 2025',
    actions: 'Restock',
    status: 'Low Stock',
  },
];

export const orderVolume = [
  {
    id: 1,
    orderPlaced: 45,
    date: 'May 13, 2025',
    orderCompleted: 39,
  },
  {
    id: 2,
    orderPlaced: 29,
    date: 'March 5, 2025',
    orderCompleted: 27,
  },
  {
    id: 3,
    orderPlaced: 32,
    date: 'March 11, 2025',
    orderCompleted: 26,
  },
  {
    id: 4,
    orderPlaced: 18,
    date: 'April 23, 2025',
    orderCompleted: 18,
  },
  {
    id: 5,
    orderPlaced: 30,
    date: 'May 23, 2025',
    orderCompleted: 15,
  },
];

export const stockTurnoer = [
  {
    id: 1,
    products: 'Necklace',
    productRemain: 24,
    productSold: 2,
  },
  {
    id: 1,
    products: 'Nike Sneakers',
    productRemain: 24,
    productSold: 2,
  },
  {
    id: 1,
    products: 'Pots',
    productRemain: 16,
    productSold: 8,
  },
  {
    id: 4,
    products: 'Corporate Shoes',
    productRemain: 24,
    productSold: 30,
  },
  {
    id: 5,
    products: 'Nike Sneakers',
    productRemain: 5,
    productSold: 14,
  },
];

export const reportSummary = [
  {
    id: 1,
    Product: 'Nike Sneakers',
    revenue: 20000,
    stockStatus: 'In Stock',
    productSold: 120,
  },
  {
    id: 2,
    Product: 'Hand Bag',
    revenue: 40000,
    stockStatus: 'Low Stock',
    productSold: 400,
  },
  {
    id: 3,
    Product: 'Vodi',
    revenue: 50000,
    stockStatus: 'In Stock',
    productSold: 450,
  },
  {
    id: 4,
    Product: 'Addidas Sneakers',
    revenue: 15000,
    stockStatus: 'In Stock',
    productSold: 100,
  },
];
export const paymentStatus = [
  {
    id: 1,
    amount: '8,000',
    date: 'May 23, 2025',
    status: 'Reconciled',
  },
  {
    id: 2,
    amount: '6,000',
    date: 'May 23, 2025',
    status: 'Unreconcile',
  },
  {
    id: 3,
    amount: '10,000',
    date: 'May 23, 2025',
    status: 'Reconciled',
  },
  {
    id: 4,
    amount: '2,000',
    date: 'May 23, 2025',
    status: 'Unreconcile',
  },
  {
    id: 5,
    amount: '8,000',
    date: 'May 23, 2025',
    status: 'Reconciled',
  },
];

export const user = {
  id: '1',
  name: `Jessie's Tees`,
  email: 'simeonstat@gmail.com',
  businessPlan: 'Premium Plan',
};

export const aboutBiz = {
  title: 'About BizEase',

  subTitle: `Running a business is hard enough — managing your orders and inventory shouldn't be. That's where BizEase comes in.`,

  sub: `We created BizEase with one simple goal: to take the stress out of business management for small and medium-sized enterprises. Whether you're juggling sales, shipping, or stock levels, BizEase gives you the tools to stay in control — all from one intuitive platform.`,

  missionHead: 'Our Mission',
  missionSub: `At BizEase, we believe powerful business tools shouldn't come with a steep learning curve. That is why we built a platform thats easy to use, efficient, and designed to grow with your business.`,

  missionSub2: `Born out of frustration with clunky spreadsheets and over-complicated software, BizEase was created to simplify daily operations — so business owners can focus on what truly matters: growing their business and serving their customers.`,

  amazingHead: 'What Makes BizEase Amazing?',
  amazingSub: `Here is what you can expect when you switch to BizEase:`,

  amazingList: [
    '✅ Smart Order Management Track orders from start to finish, keep your customers in the loop, and never miss a sale.',
    '📦 Real-Time Inventory Tracking - Know exactly what is in stock, what is running low, and when to reorder — all in real time.',
    '🔗 Seamless Integration - Easily connect with your existing tools and platforms — no tech headaches.',
    '📊 Insightful Reports & Dashboards - Get a clear picture of your business with customizable analytics and performance metrics.',
    '⏱️ Time-Saving Automation - Automate repetitive tasks and cut down on manual work, so you can focus on growth.',
    '🔒 Secure and Reliable - Your data is safe with us. BizEase uses top-grade security so you can operate with peace of mind.',
    '📱 Access Anywhere, Anytime - Manage your business from your laptop, tablet, or phone — wherever you are.',
  ],

  builtForH: 'Built for Business Owners Like You',
  builtsub: `Whether you're managing a retail shop, running an online store, or overseeing multiple warehouses, BizEase adapts to your needs — not the other way around. We're here to make your life easier, your operations smoother, and your growth unstoppable.`,

  ready: 'Ready to simplify your business?',
};
